issuer: https://token.actions.githubusercontent.com
subject: repo:chainguard-dev/image-comparison:ref:refs/heads/main
claim_pattern:
  job_workflow_ref: chainguard-dev/image-comparison/.github/workflows/gen-html.yml@refs/heads/main

permissions:
  contents: write
