name: bandit-security-linter
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  bandit:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Needed to clone source code
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.2
      - name: Run bandit
        uses: tj-actions/bandit@0aed5b3da320e0f26781e5aecbbfc1d268ff07e2 # v5.5
