name: black-formatter-lint

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Needed to clone source code
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.2
      - uses: psf/black@6fdf8a4af28071ed1d079c01122b34c5d587207a # 24.2.0
