name: pull-data

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 12 * * *' # runs at 12:00 UTC everyday

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for gitsign auth
      contents: write # Needed to commit files back to repo
    steps:
      - name: checkout repo content
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.2
      - name: setup python
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version: '3.12'
      - name: install python packages
        run: |
          python -m pip install --upgrade pipenv
          pipenv install
      - name: execute py script
        id: run
        env: 
          DATA_URL: ${{ secrets.DATA_URL }}
        run:
          pipenv run python main.py
          echo "is_git_diff=$(git diff-index --quiet HEAD -- && echo false || echo true)" >> $GITHUB_ENV
      - name: gitsign
        if: ${{ steps.run.outputs.is_git_diff == 'true' }}
        uses: chainguard-dev/actions/setup-gitsign@main
      - name: commit files
        if: ${{ steps.run.outputs.is_git_diff == 'true' }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data.csv
          git commit -m "update data"
          git push origin main
      - if: ${{ failure() && github.event_name == 'schedule' }}
        uses: rtCamp/action-slack-notify@b24d75fe0e728a4bf9fc42ee217caa686d141ee8 # v2.2.1
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_COLOR: '#8E1600'
          MSG_MINIMAL: 'true'
          SLACK_TITLE: pull-data failed.
          SLACK_MESSAGE: |
            For detailed logs: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
